# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ibm <- function(nbInd, length, prob_mut, loci, mutationMatrix, selectionMatrix) {
    .Call('_IBMselection_ibm', PACKAGE = 'IBMselection', nbInd, length, prob_mut, loci, mutationMatrix, selectionMatrix)
}

